import { useEffect, useState } from "react";
import {
  Search,
  Target,
  PenTool,
  BarChart3,
  CheckCircle2,
  Loader2,
  Download,
  Copy,
  Check,
  Users,
  MousePointerClick,
  Heart,
  TrendingUp,
  FileArchive,
} from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { campaignPdfFilename, generateCampaignPdf } from "@/lib/marketing-genius/generateCampaignPdf";
import { downloadCampaignZipLocal } from "@/lib/marketing-genius/buildCampaignZip";
import {
  AGENT_STATUS_MESSAGES,
  type AgentName,
  type AgentState,
  type FullCampaign,
} from "@/types/marketing-genius";
import { cn } from "@/lib/utils";

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button
      type="button"
      onClick={handleCopy}
      className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground transition-colors"
    >
      {copied ? <Check className="w-3.5 h-3.5 text-green-600" /> : <Copy className="w-3.5 h-3.5" />}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

interface CampaignResultsProps {
  campaign: FullCampaign;
}

export function CampaignResults({ campaign }: CampaignResultsProps) {
  const { research, strategy, content, analytics, input } = campaign;
  const [downloadingPdf, setDownloadingPdf] = useState(false);
  const [downloadingZip, setDownloadingZip] = useState(false);

  const handleDownloadPdf = () => {
    setDownloadingPdf(true);
    try {
      generateCampaignPdf(campaign, campaignPdfFilename(input.companyName));
    } catch {
      alert("PDF generation failed. Please try again.");
    } finally {
      setDownloadingPdf(false);
    }
  };

  const handleDownloadZip = () => {
    setDownloadingZip(true);
    try {
      downloadCampaignZipLocal(campaign);
    } catch {
      alert("ZIP download failed. Please try again.");
    } finally {
      setDownloadingZip(false);
    }
  };

  const metrics = [
    { label: "Est. Reach", value: analytics.estimatedReach, icon: Users },
    { label: "Est. CTR", value: analytics.estimatedCTR, icon: MousePointerClick },
    { label: "Engagement", value: analytics.engagementForecast, icon: Heart },
    { label: "ROI", value: analytics.roiProjection, icon: TrendingUp },
  ];

  return (
    <Card className="shadow-md border-border/80 w-full">
        <CardHeader className="pb-4">
          <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4">
            <div className="space-y-1">
              <CardTitle className="text-xl">Campaign Package: {input.companyName}</CardTitle>
              <CardDescription>
                {strategy.campaignName} · Generated by 4 AI agents ·{" "}
                {new Date(campaign.createdAt).toLocaleString()}
              </CardDescription>
              <p className="text-xs text-muted-foreground font-mono">ID: {campaign.id}</p>
            </div>
            <div className="flex flex-wrap gap-2 shrink-0">
                <Button onClick={handleDownloadPdf} variant="outline" size="sm" disabled={downloadingPdf}>
                  {downloadingPdf ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      PDF…
                    </>
                  ) : (
                    <>
                      <Download className="w-4 h-4 mr-2" />
                      Download PDF
                    </>
                  )}
                </Button>
                <Button onClick={handleDownloadZip} variant="outline" size="sm" disabled={downloadingZip}>
                  {downloadingZip ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      ZIP…
                    </>
                  ) : (
                    <>
                      <FileArchive className="w-4 h-4 mr-2" />
                      Download ZIP
                    </>
                  )}
                </Button>
              </div>
            </div>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="research">
            <TabsList className="w-full flex flex-wrap h-auto gap-1 bg-muted/60 p-1">
              <TabsTrigger value="research" className="flex-1 sm:flex-none">
                Research
              </TabsTrigger>
              <TabsTrigger value="strategy" className="flex-1 sm:flex-none">
                Strategy
              </TabsTrigger>
              <TabsTrigger value="content" className="flex-1 sm:flex-none">
                Content
              </TabsTrigger>
              <TabsTrigger value="analytics" className="flex-1 sm:flex-none">
                Analytics
              </TabsTrigger>
            </TabsList>

            <TabsContent value="research" className="mt-6 space-y-6">
              <p className="text-muted-foreground leading-relaxed">{research.summary}</p>
              <div>
                <h4 className="font-semibold mb-3">Market Trends</h4>
                <ul className="space-y-2">
                  {research.marketTrends.map((t, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-primary mt-0.5">•</span>
                      <span>{t}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Competitors</h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {research.competitors.map((c, i) => (
                    <div key={i} className="rounded-lg border border-border/80 bg-muted/30 p-4 space-y-2">
                      <p className="font-medium">{c.name}</p>
                      <p className="text-sm text-muted-foreground">
                        <span className="font-medium text-foreground">Strength:</span> {c.strength}
                      </p>
                      <p className="text-sm text-muted-foreground">
                        <span className="font-medium text-foreground">Weakness:</span> {c.weakness}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Audience Insights</h4>
                <ul className="space-y-2">
                  {research.audienceInsights.map((item, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-primary">→</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Growth Opportunities</h4>
                <ul className="space-y-2">
                  {research.opportunities.map((item, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-primary">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </TabsContent>

            <TabsContent value="strategy" className="mt-6 space-y-6">
              <h3 className="text-xl font-bold">{strategy.campaignName}</h3>
              <div>
                <h4 className="font-semibold mb-3">Objectives</h4>
                <ul className="space-y-2">
                  {strategy.objectives.map((o, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-primary">•</span>
                      <span>{o}</span>
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Channel Plan</h4>
                <div className="space-y-3">
                  {strategy.channels.map((ch, i) => (
                    <div key={i} className="rounded-lg border border-border/80 bg-muted/20 p-4">
                      <p className="font-medium text-sm">{ch.name}</p>
                      <p className="text-sm text-muted-foreground mt-1">{ch.rationale}</p>
                      <ul className="mt-2 space-y-1">
                        {ch.tactics.map((t, j) => (
                          <li key={j} className="text-xs text-muted-foreground flex gap-2">
                            <span className="text-primary">·</span>
                            {t}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Timeline</h4>
                <div className="space-y-3">
                  {strategy.timeline.map((phase, i) => (
                    <div key={i} className="rounded-lg border border-border/80 p-4">
                      <div className="flex items-center gap-2 mb-2">
                        <Badge variant="outline">{phase.phase}</Badge>
                        <span className="text-xs text-muted-foreground">{phase.duration}</span>
                      </div>
                      <ul className="space-y-1">
                        {phase.activities.map((a, j) => (
                          <li key={j} className="text-sm text-muted-foreground flex gap-2">
                            <span className="text-primary">•</span>
                            {a}
                          </li>
                        ))}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Budget Allocation</h4>
                <div className="space-y-3">
                  {strategy.budgetAllocation.map((b, i) => (
                    <div key={i}>
                      <div className="flex justify-between text-sm mb-1.5">
                        <span className="font-medium">{b.category}</span>
                        <span className="text-muted-foreground">
                          {b.percentage}% · {b.amount}
                        </span>
                      </div>
                      <div className="h-2 rounded-full bg-muted overflow-hidden">
                        <div
                          className="h-full rounded-full bg-gradient-primary transition-all"
                          style={{ width: `${b.percentage}%` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Key Messages</h4>
                <ul className="space-y-2">
                  {strategy.keyMessages.map((m, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-primary">→</span>
                      <span>{m}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </TabsContent>

            <TabsContent value="content" className="mt-6 space-y-6">
              <div>
                <h4 className="font-semibold mb-3">Ad Variants</h4>
                <div className="space-y-3">
                  {content.ads.map((ad, i) => (
                    <div key={i} className="rounded-lg border border-border/80 bg-card p-4 space-y-2">
                      <div className="flex justify-between items-start gap-3">
                        <h5 className="font-semibold">{ad.headline}</h5>
                        <CopyButton text={`${ad.headline}\n\n${ad.body}\n\nCTA: ${ad.cta}`} />
                      </div>
                      <p className="text-sm text-muted-foreground leading-relaxed">{ad.body}</p>
                      <Badge className="bg-primary/10 text-primary border-primary/20 hover:bg-primary/10">
                        {ad.cta}
                      </Badge>
                    </div>
                  ))}
                </div>
              </div>
              <div>
                <h4 className="font-semibold mb-3">Social Posts</h4>
                <div className="space-y-3">
                  {content.socialPosts.map((post, i) => (
                    <div key={i} className="rounded-lg border border-border/80 bg-muted/20 p-4 space-y-2">
                      <div className="flex justify-between items-center">
                        <Badge variant="outline" className="font-medium">
                          {post.platform}
                        </Badge>
                        <CopyButton text={post.text} />
                      </div>
                      <p className="text-sm whitespace-pre-wrap leading-relaxed">{post.text}</p>
                      {post.hashtags?.length > 0 && (
                        <p className="text-xs text-primary">
                          {post.hashtags.map((h) => (h.startsWith("#") ? h : `#${h}`)).join(" ")}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
              {content.emails?.length > 0 && (
                <div>
                  <h4 className="font-semibold mb-3">Email Drafts</h4>
                  <div className="space-y-3">
                    {content.emails.map((email, i) => (
                      <div key={i} className="rounded-lg border border-border/80 bg-card p-4 space-y-2">
                        <div className="flex justify-between items-start gap-3">
                          <p className="font-semibold text-sm">Subject: {email.subject}</p>
                          <CopyButton text={`Subject: ${email.subject}\n\n${email.body}`} />
                        </div>
                        <p className="text-xs text-muted-foreground italic">{email.preview}</p>
                        <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
                          {email.body}
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </TabsContent>

            <TabsContent value="analytics" className="mt-6 space-y-6">
              <div className="grid grid-cols-2 gap-3">
                {metrics.map((s) => (
                  <div
                    key={s.label}
                    className="rounded-lg border border-border/80 bg-muted/30 p-4 text-center space-y-2"
                  >
                    <div className="flex justify-center">
                      <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary">
                        <s.icon className="w-4 h-4" />
                      </div>
                    </div>
                    <p className="text-xs text-muted-foreground">{s.label}</p>
                    <p className="font-semibold text-sm">{s.value}</p>
                  </div>
                ))}
              </div>
              {analytics.kpis?.length > 0 && (
                <div>
                  <h4 className="font-semibold mb-3">Key Performance Indicators</h4>
                  <div className="rounded-lg border border-border/80 overflow-hidden">
                    <table className="w-full text-sm">
                      <thead className="bg-muted/50">
                        <tr>
                          <th className="text-left p-3 font-medium">Metric</th>
                          <th className="text-left p-3 font-medium">Target</th>
                          <th className="text-left p-3 font-medium">Benchmark</th>
                        </tr>
                      </thead>
                      <tbody>
                        {analytics.kpis.map((k, i) => (
                          <tr key={i} className="border-t border-border/60">
                            <td className="p-3">{k.metric}</td>
                            <td className="p-3 text-muted-foreground">{k.target}</td>
                            <td className="p-3 text-muted-foreground">{k.benchmark}</td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              )}
              <div>
                <h4 className="font-semibold mb-3">Recommendations</h4>
                <ul className="space-y-2">
                  {analytics.recommendations.map((r, i) => (
                    <li key={i} className="flex gap-2 text-sm">
                      <span className="text-primary">→</span>
                      <span>{r}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>
  );
}

const ICONS = { research: Search, strategy: Target, content: PenTool, analytics: BarChart3 };

interface AgentPipelineProps {
  agents: AgentState[];
  isGenerating: boolean;
}

export function AgentPipeline({ agents, isGenerating }: AgentPipelineProps) {
  const runningAgent = agents.find((a) => a.status === "running");
  const [messageIndex, setMessageIndex] = useState(0);

  useEffect(() => {
    if (!runningAgent) return;
    const interval = setInterval(() => setMessageIndex((i) => i + 1), 2500);
    return () => clearInterval(interval);
  }, [runningAgent?.name]);

  const statusMessage = runningAgent
    ? AGENT_STATUS_MESSAGES[runningAgent.name as AgentName][messageIndex % AGENT_STATUS_MESSAGES[runningAgent.name as AgentName].length]
    : null;

  const show = isGenerating || agents.some((a) => a.status !== "pending");
  if (!show) return null;

  return (
    <div className="space-y-3 w-full">
      <div className="flex items-center justify-between gap-2">
        <h2 className="text-lg font-semibold">AI Agent Pipeline</h2>
        {statusMessage && (
          <p className="text-xs text-muted-foreground animate-pulse truncate max-w-[50%]">{statusMessage}</p>
        )}
      </div>
      <div className="grid grid-cols-2 xl:grid-cols-4 gap-3 w-full">
        {agents.map((agent, index) => {
          const Icon = ICONS[agent.name];
          const isRunning = agent.status === "running";
          const isComplete = agent.status === "complete";
          const isError = agent.status === "error";

          return (
            <Card
              key={agent.name}
              className={cn(
                "transition-all",
                isRunning && "border-primary/50 ring-2 ring-primary/20 shadow-md",
                isComplete && "border-green-500/20 bg-green-500/[0.02]"
              )}
            >
              <CardHeader className="pb-3 pt-4 px-4">
                <div className="flex items-start justify-between gap-2">
                  <div
                    className={cn(
                      "flex h-9 w-9 items-center justify-center rounded-lg shrink-0",
                      isComplete && "bg-green-500/10 text-green-600",
                      isRunning && "bg-primary/10 text-primary",
                      !isComplete && !isRunning && "bg-muted text-muted-foreground"
                    )}
                  >
                    {isComplete ? (
                      <CheckCircle2 className="w-4 h-4" />
                    ) : isRunning ? (
                      <Loader2 className="w-4 h-4 animate-spin" />
                    ) : (
                      <Icon className="w-4 h-4" />
                    )}
                  </div>
                  <Badge
                    variant={isComplete ? "default" : isRunning ? "secondary" : isError ? "destructive" : "outline"}
                    className={cn("text-xs shrink-0", isComplete && "bg-primary")}
                  >
                    {isComplete ? "Complete" : isRunning ? "Running" : isError ? "Error" : "Waiting"}
                  </Badge>
                </div>
                <CardTitle className="text-sm font-semibold leading-tight">
                  {index + 1}. {agent.label}
                </CardTitle>
                <CardDescription className="text-xs leading-relaxed">{agent.description}</CardDescription>
              </CardHeader>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
