import { useState } from "react";
import { Sparkles, RotateCcw, Search, Target, PenTool, BarChart3, CheckCircle2, Loader2, Download, Copy, Check, AlertCircle, Bot, Zap } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useMarketingGeniusStream, downloadCampaignZip } from "@/hooks/useMarketingGeniusStream";
import { CHANNEL_OPTIONS, DEMO_COMPANY, type CompanyInput, type FullCampaign, type AgentState } from "@/types/marketing-genius";

const ICONS = { research: Search, strategy: Target, content: PenTool, analytics: BarChart3 };

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  const handleCopy = async () => {
    await navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <button onClick={handleCopy} className="inline-flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground">
      {copied ? <Check className="w-3.5 h-3.5 text-green-500" /> : <Copy className="w-3.5 h-3.5" />}
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

function AgentPipeline({ agents, isGenerating }: { agents: AgentState[]; isGenerating: boolean }) {
  const show = isGenerating || agents.some((a) => a.status !== "pending");
  if (!show) return null;

  return (
    <div className="space-y-4">
      <h2 className="text-xl font-semibold">AI Agent Pipeline</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {agents.map((agent, index) => {
          const Icon = ICONS[agent.name];
          const isRunning = agent.status === "running";
          const variant = agent.status === "complete" ? "default" : isRunning ? "secondary" : agent.status === "error" ? "destructive" : "outline";
          return (
            <Card key={agent.name} className={isRunning ? "ring-2 ring-primary" : ""}>
              <CardHeader className="pb-2">
                <div className="flex items-start justify-between">
                  <div className={`flex h-10 w-10 items-center justify-center rounded-lg ${agent.status === "complete" ? "bg-green-500/10 text-green-600" : isRunning ? "bg-primary/10 text-primary" : "bg-muted text-muted-foreground"}`}>
                    {agent.status === "complete" ? <CheckCircle2 className="w-5 h-5" /> : isRunning ? <Loader2 className="w-5 h-5 animate-spin" /> : <Icon className="w-5 h-5" />}
                  </div>
                  <Badge variant={variant as "default" | "secondary" | "destructive" | "outline"}>
                    {agent.status === "complete" ? "Complete" : isRunning ? "Running" : agent.status === "error" ? "Error" : "Waiting"}
                  </Badge>
                </div>
                <CardTitle className="text-base">Agent {index + 1}: {agent.label}</CardTitle>
                <CardDescription>{agent.description}</CardDescription>
              </CardHeader>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

function CampaignResults({ campaign }: { campaign: FullCampaign }) {
  const { research, strategy, content, analytics, input } = campaign;

  const handleDownload = async () => {
    try {
      await downloadCampaignZip(campaign.id);
    } catch {
      alert("Download failed. Please try again.");
    }
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <CardTitle>Campaign Package: {input.companyName}</CardTitle>
            <CardDescription>Generated by 4 AI agents · {new Date(campaign.createdAt).toLocaleString()}</CardDescription>
          </div>
          <Button onClick={handleDownload} variant="outline">
            <Download className="w-4 h-4 mr-2" /> Download ZIP
          </Button>
        </div>
      </CardHeader>
      <CardContent>
        <Tabs defaultValue="research">
          <TabsList className="flex flex-wrap h-auto gap-1">
            <TabsTrigger value="research">Research</TabsTrigger>
            <TabsTrigger value="strategy">Strategy</TabsTrigger>
            <TabsTrigger value="content">Content</TabsTrigger>
            <TabsTrigger value="analytics">Analytics</TabsTrigger>
          </TabsList>
          <TabsContent value="research" className="mt-4 space-y-4">
            <p className="text-muted-foreground leading-relaxed">{research.summary}</p>
            <div><h4 className="font-semibold mb-2">Market Trends</h4><ul className="space-y-1">{research.marketTrends.map((t, i) => <li key={i}>• {t}</li>)}</ul></div>
            <div><h4 className="font-semibold mb-2">Competitors</h4>{research.competitors.map((c, i) => (
              <div key={i} className="rounded-lg border p-3 mb-2"><p className="font-medium">{c.name}</p><p className="text-sm text-muted-foreground">Strength: {c.strength}</p><p className="text-sm text-muted-foreground">Weakness: {c.weakness}</p></div>
            ))}</div>
          </TabsContent>
          <TabsContent value="strategy" className="mt-4 space-y-4">
            <h3 className="text-xl font-bold">{strategy.campaignName}</h3>
            <div><h4 className="font-semibold mb-2">Objectives</h4><ul>{strategy.objectives.map((o, i) => <li key={i}>• {o}</li>)}</ul></div>
            <div><h4 className="font-semibold mb-2">Budget Allocation</h4>{strategy.budgetAllocation.map((b, i) => (
              <div key={i} className="mb-2"><div className="flex justify-between text-sm"><span>{b.category}</span><span>{b.percentage}% · {b.amount}</span></div><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary" style={{ width: `${b.percentage}%` }} /></div></div>
            ))}</div>
          </TabsContent>
          <TabsContent value="content" className="mt-4 space-y-4">
            {content.ads.map((ad, i) => (
              <div key={i} className="rounded-lg border p-4">
                <div className="flex justify-between"><h5 className="font-semibold">{ad.headline}</h5><CopyButton text={`${ad.headline}\n\n${ad.body}\n\nCTA: ${ad.cta}`} /></div>
                <p className="mt-2 text-muted-foreground">{ad.body}</p>
                <Badge className="mt-2">{ad.cta}</Badge>
              </div>
            ))}
            {content.socialPosts.map((post, i) => (
              <div key={i} className="rounded-lg border p-4">
                <div className="flex justify-between"><Badge variant="outline">{post.platform}</Badge><CopyButton text={post.text} /></div>
                <p className="mt-2 whitespace-pre-wrap">{post.text}</p>
              </div>
            ))}
          </TabsContent>
          <TabsContent value="analytics" className="mt-4 space-y-4">
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
              {[
                { label: "Est. Reach", value: analytics.estimatedReach },
                { label: "Est. CTR", value: analytics.estimatedCTR },
                { label: "Engagement", value: analytics.engagementForecast },
                { label: "ROI", value: analytics.roiProjection },
              ].map((s, i) => (
                <div key={i} className="rounded-lg border p-4 text-center"><p className="text-xs text-muted-foreground">{s.label}</p><p className="font-semibold mt-1">{s.value}</p></div>
              ))}
            </div>
            <div><h4 className="font-semibold mb-2">Recommendations</h4><ul>{analytics.recommendations.map((r, i) => <li key={i}>→ {r}</li>)}</ul></div>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}

export default function MarketingGeniusPage() {
  const { agents, campaign, isGenerating, error, generate, reset } = useMarketingGeniusStream();
  const [form, setForm] = useState<CompanyInput>(DEMO_COMPANY);

  const toggleChannel = (channel: string) => {
    setForm((prev) => ({
      ...prev,
      channels: prev.channels.includes(channel) ? prev.channels.filter((c) => c !== channel) : [...prev.channels, channel],
    }));
  };

  return (
    <div className="container max-w-6xl py-8 space-y-8">
      <div className="text-center space-y-4">
        <Badge variant="secondary" className="gap-1"><Bot className="w-3.5 h-3.5" /> Multi-Agent AI System</Badge>
        <h1 className="text-4xl font-bold tracking-tight">MarketingGenius AI</h1>
        <p className="text-muted-foreground max-w-2xl mx-auto">
          Four specialized AI agents collaborate to research your market, craft strategy, generate content, and forecast ROI.
        </p>
        <div className="flex flex-wrap justify-center gap-2">
          {["Research", "Strategy", "Content", "Analytics"].map((a) => (
            <Badge key={a} variant="outline" className="gap-1"><Zap className="w-3 h-3" />{a} Agent</Badge>
          ))}
        </div>
      </div>

      {error && (
        <div className="flex items-start gap-3 rounded-lg border border-destructive/50 bg-destructive/10 p-4">
          <AlertCircle className="w-5 h-5 text-destructive shrink-0" />
          <div>
            <p className="font-medium text-destructive">Generation failed</p>
            <p className="text-sm text-muted-foreground mt-1">{error}</p>
            <button onClick={reset} className="text-sm underline mt-2">Try again</button>
          </div>
        </div>
      )}

      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <div>
              <CardTitle>Company Details</CardTitle>
              <CardDescription>Tell our AI agents about your business</CardDescription>
            </div>
            <Button variant="ghost" size="sm" onClick={() => setForm(DEMO_COMPANY)}>
              <RotateCcw className="w-4 h-4 mr-1" /> Load Demo
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          <form onSubmit={(e) => { e.preventDefault(); if (form.channels.length) generate(form); }} className="space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2"><Label>Company Name</Label><Input value={form.companyName} onChange={(e) => setForm({ ...form, companyName: e.target.value })} required /></div>
              <div className="space-y-2"><Label>Industry</Label><Input value={form.industry} onChange={(e) => setForm({ ...form, industry: e.target.value })} required /></div>
            </div>
            <div className="space-y-2"><Label>Product / Service</Label><Textarea value={form.productService} onChange={(e) => setForm({ ...form, productService: e.target.value })} required /></div>
            <div className="space-y-2"><Label>Target Audience</Label><Textarea value={form.targetAudience} onChange={(e) => setForm({ ...form, targetAudience: e.target.value })} required /></div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="space-y-2"><Label>Campaign Goal</Label><Input value={form.campaignGoal} onChange={(e) => setForm({ ...form, campaignGoal: e.target.value })} required /></div>
              <div className="space-y-2"><Label>Budget Range</Label><Input value={form.budgetRange} onChange={(e) => setForm({ ...form, budgetRange: e.target.value })} required /></div>
            </div>
            <div className="space-y-2">
              <Label>Preferred Channels</Label>
              <div className="flex flex-wrap gap-2">
                {CHANNEL_OPTIONS.map((ch) => (
                  <Button key={ch} type="button" size="sm" variant={form.channels.includes(ch) ? "default" : "outline"} onClick={() => toggleChannel(ch)}>{ch}</Button>
                ))}
              </div>
            </div>
            <Button type="submit" size="lg" className="w-full" disabled={isGenerating || !form.channels.length}>
              <Sparkles className="w-5 h-5 mr-2" />
              {isGenerating ? "Generating Campaign..." : "Generate Campaign"}
            </Button>
          </form>
        </CardContent>
      </Card>

      <AgentPipeline agents={agents} isGenerating={isGenerating} />
      {campaign && <CampaignResults campaign={campaign} />}
    </div>
  );
}
